server:
  port: 8100
  servlet:
    context-path: /api
spring:
  profiles:
    active: local
  application:
    name: shuke-picture-be
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shuke_picture
    username: root
    password: root
  # 分表配置
#  shardingsphere:
#    datasource:
#      names: shuke_picture
#      shuke_picture:
#        url: jdbc:mysql://localhost:3306/shuke_picture
#        username: root
#        password: root
#        driver-class-name: com.mysql.cj.jdbc.Driver
#    rules:
#      sharding:
#        tables:
#          picture:
#            actual-data-nodes: shuke_picture.picture # 指定逻辑表,实际数据节点
#              # 这个地方 本来是shuke_picture.picture{0..2}  这样的形式，但现在是根据spaceId进行分表，而spaceId是Long 类型
#              # 数字太大，并且不连续，所以这里先写死，自定义一个分表管理器，在项目初始化的时候指定分表范围
#            table-strategy: # 分表策略
#              standard:
#                sharding-algorithm-name: picture_sharding_algorithm  # 指定分表算法
#                sharding-column: space_id # 分表键
#          sharding-algorithms:
#            picture_sharding_algorithm:
#              type: CLASS_BASED
#              props:
#                strategy: standard
#                algorithm-class-name: com.shuke.shukepicturebe.manager.sharding.PictureShardingAlgorithm
#    props:
#      sql-show: true

  # 文件上传
  servlet:
    multipart:
      max-file-size: 10MB
  # Redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
    lettuce:
      pool:
        # 连接池中的最大数据库连接数
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000

# mybatis-plus 相关配置
mybatis-plus:
  configuration:
    # 不会将下划线 转换为 驼峰命名发  如：user_id  不会转换成  userId
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0

# knife4j 相关配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources: com.shuke.shukepicturebe.controller
